export const PLANS = {
  free: {
    name: 'Explorador',
    price: 0,
    monthlyGenerations: 5,
    outputFormats: ['tweets', 'linkedin', 'reels', 'carousel'],
    historyDays: 7,
    brandVoice: false,
    multipleClients: false,
    exportBulk: false,
    variations: false,
  },
  creator: {
    name: 'Creador',
    price: 12,
    stripeMonthlyPriceId: import.meta.env.VITE_STRIPE_CREATOR_PRICE_ID,
    monthlyGenerations: 30,
    outputFormats: ['tweets', 'linkedin', 'reels', 'carousel', 'newsletter', 'blog'],
    historyDays: 60,
    brandVoice: true,
    multipleClients: false,
    exportBulk: false,
    variations: false,
  },
  agency: {
    name: 'Agencia',
    price: 29,
    stripeMonthlyPriceId: import.meta.env.VITE_STRIPE_AGENCY_PRICE_ID,
    monthlyGenerations: Infinity,
    outputFormats: ['tweets', 'linkedin', 'reels', 'carousel', 'newsletter', 'blog'],
    historyDays: Infinity,
    brandVoice: true,
    multipleClients: true,
    exportBulk: true,
    variations: true,
  },
}
